package vn.com.vti.bookshop.entity;

import java.util.Date;

public class CardCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.card_company.card_company_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String cardCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.card_company.card_company_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String cardCompanyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.card_company.prefecture
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String prefecture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.card_company.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.card_company.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.card_company.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.card_company.card_company_id
     *
     * @return the value of public.card_company.card_company_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getCardCompanyId() {
        return cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.card_company.card_company_id
     *
     * @param cardCompanyId the value for public.card_company.card_company_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCardCompanyId(String cardCompanyId) {
        this.cardCompanyId = cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.card_company.card_company_name
     *
     * @return the value of public.card_company.card_company_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getCardCompanyName() {
        return cardCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.card_company.card_company_name
     *
     * @param cardCompanyName the value for public.card_company.card_company_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCardCompanyName(String cardCompanyName) {
        this.cardCompanyName = cardCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.card_company.prefecture
     *
     * @return the value of public.card_company.prefecture
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getPrefecture() {
        return prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.card_company.prefecture
     *
     * @param prefecture the value for public.card_company.prefecture
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setPrefecture(String prefecture) {
        this.prefecture = prefecture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.card_company.update_at
     *
     * @return the value of public.card_company.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.card_company.update_at
     *
     * @param updateAt the value for public.card_company.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.card_company.create_at
     *
     * @return the value of public.card_company.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.card_company.create_at
     *
     * @param createAt the value for public.card_company.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.card_company.product_id
     *
     * @return the value of public.card_company.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.card_company.product_id
     *
     * @param productId the value for public.card_company.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}