package vn.com.vti.bookshop.entity;

import java.util.Date;

public class Character {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.character.character_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer characterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.character.character_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String characterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.character.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.character.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.character.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.character.character_id
     *
     * @return the value of public.character.character_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.character.character_id
     *
     * @param characterId the value for public.character.character_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.character.character_name
     *
     * @return the value of public.character.character_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getCharacterName() {
        return characterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.character.character_name
     *
     * @param characterName the value for public.character.character_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCharacterName(String characterName) {
        this.characterName = characterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.character.update_at
     *
     * @return the value of public.character.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.character.update_at
     *
     * @param updateAt the value for public.character.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.character.create_at
     *
     * @return the value of public.character.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.character.create_at
     *
     * @param createAt the value for public.character.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.character.product_id
     *
     * @return the value of public.character.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.character.product_id
     *
     * @param productId the value for public.character.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}