package vn.com.vti.bookshop.entity;

import java.util.Date;

public class MemberCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.member_card_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private Integer memberCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.member_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.card_company_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private String cardCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.card_number
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private String cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.expire_year
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private String expireYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.expire_month
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private String expireMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.update_at
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.create_at
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member_card.product_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.member_card_id
     *
     * @return the value of public.member_card.member_card_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public Integer getMemberCardId() {
        return memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.member_card_id
     *
     * @param memberCardId the value for public.member_card.member_card_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setMemberCardId(Integer memberCardId) {
        this.memberCardId = memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.member_id
     *
     * @return the value of public.member_card.member_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.member_id
     *
     * @param memberId the value for public.member_card.member_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.card_company_id
     *
     * @return the value of public.member_card.card_company_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public String getCardCompanyId() {
        return cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.card_company_id
     *
     * @param cardCompanyId the value for public.member_card.card_company_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setCardCompanyId(String cardCompanyId) {
        this.cardCompanyId = cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.card_number
     *
     * @return the value of public.member_card.card_number
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.card_number
     *
     * @param cardNumber the value for public.member_card.card_number
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.expire_year
     *
     * @return the value of public.member_card.expire_year
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public String getExpireYear() {
        return expireYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.expire_year
     *
     * @param expireYear the value for public.member_card.expire_year
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setExpireYear(String expireYear) {
        this.expireYear = expireYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.expire_month
     *
     * @return the value of public.member_card.expire_month
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public String getExpireMonth() {
        return expireMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.expire_month
     *
     * @param expireMonth the value for public.member_card.expire_month
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setExpireMonth(String expireMonth) {
        this.expireMonth = expireMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.update_at
     *
     * @return the value of public.member_card.update_at
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.update_at
     *
     * @param updateAt the value for public.member_card.update_at
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.create_at
     *
     * @return the value of public.member_card.create_at
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.create_at
     *
     * @param createAt the value for public.member_card.create_at
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member_card.product_id
     *
     * @return the value of public.member_card.product_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member_card.product_id
     *
     * @param productId the value for public.member_card.product_id
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}