package vn.com.vti.bookshop.entity;

import java.util.Date;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.member_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.password
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.last_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.first_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.post_code
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.address
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.birthday
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.tel_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.email_address
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.regis_datetime
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date regisDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.member.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.member_id
     *
     * @return the value of public.member.member_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.member_id
     *
     * @param memberId the value for public.member.member_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.password
     *
     * @return the value of public.member.password
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.password
     *
     * @param password the value for public.member.password
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.last_name
     *
     * @return the value of public.member.last_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.last_name
     *
     * @param lastName the value for public.member.last_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.first_name
     *
     * @return the value of public.member.first_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.first_name
     *
     * @param firstName the value for public.member.first_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.post_code
     *
     * @return the value of public.member.post_code
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.post_code
     *
     * @param postCode the value for public.member.post_code
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.address
     *
     * @return the value of public.member.address
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.address
     *
     * @param address the value for public.member.address
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.birthday
     *
     * @return the value of public.member.birthday
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.birthday
     *
     * @param birthday the value for public.member.birthday
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.tel_no
     *
     * @return the value of public.member.tel_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.tel_no
     *
     * @param telNo the value for public.member.tel_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.email_address
     *
     * @return the value of public.member.email_address
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.email_address
     *
     * @param emailAddress the value for public.member.email_address
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.regis_datetime
     *
     * @return the value of public.member.regis_datetime
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getRegisDatetime() {
        return regisDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.regis_datetime
     *
     * @param regisDatetime the value for public.member.regis_datetime
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setRegisDatetime(Date regisDatetime) {
        this.regisDatetime = regisDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.update_at
     *
     * @return the value of public.member.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.update_at
     *
     * @param updateAt the value for public.member.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.create_at
     *
     * @return the value of public.member.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.create_at
     *
     * @param createAt the value for public.member.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.member.product_id
     *
     * @return the value of public.member.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.member.product_id
     *
     * @param productId the value for public.member.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}