package vn.com.vti.bookshop.entity;

import java.util.Date;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.order_detail_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer orderDetailNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.order_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.item_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer itemNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.order_detail_no
     *
     * @return the value of public.order_detail.order_detail_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getOrderDetailNo() {
        return orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.order_detail_no
     *
     * @param orderDetailNo the value for public.order_detail.order_detail_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setOrderDetailNo(Integer orderDetailNo) {
        this.orderDetailNo = orderDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.order_no
     *
     * @return the value of public.order_detail.order_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.order_no
     *
     * @param orderNo the value for public.order_detail.order_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.product_id
     *
     * @return the value of public.order_detail.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.product_id
     *
     * @param productId the value for public.order_detail.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.item_no
     *
     * @return the value of public.order_detail.item_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.item_no
     *
     * @param itemNo the value for public.order_detail.item_no
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setItemNo(Integer itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.update_at
     *
     * @return the value of public.order_detail.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.update_at
     *
     * @param updateAt the value for public.order_detail.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.create_at
     *
     * @return the value of public.order_detail.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.create_at
     *
     * @param createAt the value for public.order_detail.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}