package vn.com.vti.bookshop.entity;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.product_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.price
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.character_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer characterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.category_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private String categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.discount
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.on_sale_date
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date onSaleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.product.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    private Date createAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_id
     *
     * @return the value of public.product.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_id
     *
     * @param productId the value for public.product.product_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.product_name
     *
     * @return the value of public.product.product_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.product_name
     *
     * @param productName the value for public.product.product_name
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.price
     *
     * @return the value of public.product.price
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.price
     *
     * @param price the value for public.product.price
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.character_id
     *
     * @return the value of public.product.character_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.character_id
     *
     * @param characterId the value for public.product.character_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.category_id
     *
     * @return the value of public.product.category_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.category_id
     *
     * @param categoryId the value for public.product.category_id
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.discount
     *
     * @return the value of public.product.discount
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.discount
     *
     * @param discount the value for public.product.discount
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.on_sale_date
     *
     * @return the value of public.product.on_sale_date
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getOnSaleDate() {
        return onSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.on_sale_date
     *
     * @param onSaleDate the value for public.product.on_sale_date
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setOnSaleDate(Date onSaleDate) {
        this.onSaleDate = onSaleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.update_at
     *
     * @return the value of public.product.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.update_at
     *
     * @param updateAt the value for public.product.update_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.product.create_at
     *
     * @return the value of public.product.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.product.create_at
     *
     * @param createAt the value for public.product.create_at
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
}