package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.AlcoholType;
import vn.com.vti.bookshop.entity.AlcoholTypeExample;

public interface AlcoholTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    long countByExample(AlcoholTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByExample(AlcoholTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insert(AlcoholType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insertSelective(AlcoholType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    List<AlcoholType> selectByExample(AlcoholTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    AlcoholType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExampleSelective(@Param("row") AlcoholType row, @Param("example") AlcoholTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExample(@Param("row") AlcoholType row, @Param("example") AlcoholTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKeySelective(AlcoholType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKey(AlcoholType row);
}