package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.Alcohol;
import vn.com.vti.bookshop.entity.AlcoholExample;

public interface AlcoholMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    long countByExample(AlcoholExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByExample(AlcoholExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insert(Alcohol row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insertSelective(Alcohol row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    List<Alcohol> selectByExample(AlcoholExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    Alcohol selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExampleSelective(@Param("row") Alcohol row, @Param("example") AlcoholExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExample(@Param("row") Alcohol row, @Param("example") AlcoholExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKeySelective(Alcohol row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.alcohol
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKey(Alcohol row);
}