package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.Customer;
import vn.com.vti.bookshop.entity.CustomerExample;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int deleteByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int insert(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int insertSelective(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    Customer selectByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int updateByExampleSelective(@Param("row") Customer row, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int updateByExample(@Param("row") Customer row, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int updateByPrimaryKeySelective(Customer row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.customer
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    int updateByPrimaryKey(Customer row);
}