package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.PaymentType;
import vn.com.vti.bookshop.entity.PaymentTypeExample;

public interface PaymentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    long countByExample(PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByExample(PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insert(PaymentType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insertSelective(PaymentType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    List<PaymentType> selectByExample(PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    PaymentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExampleSelective(@Param("row") PaymentType row, @Param("example") PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExample(@Param("row") PaymentType row, @Param("example") PaymentTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKeySelective(PaymentType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.payment_type
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKey(PaymentType row);
}