package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.ShippingMethod;
import vn.com.vti.bookshop.entity.ShippingMethodExample;

public interface ShippingMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    long countByExample(ShippingMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByExample(ShippingMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insert(ShippingMethod row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int insertSelective(ShippingMethod row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    List<ShippingMethod> selectByExample(ShippingMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    ShippingMethod selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExampleSelective(@Param("row") ShippingMethod row, @Param("example") ShippingMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByExample(@Param("row") ShippingMethod row, @Param("example") ShippingMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKeySelective(ShippingMethod row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    int updateByPrimaryKey(ShippingMethod row);
}