package vn.com.vti.bookshop.entity;

public class AlcoholType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol_type.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol_type.type_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol_type.id
     *
     * @return the value of public.alcohol_type.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol_type.id
     *
     * @param id the value for public.alcohol_type.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol_type.type_name
     *
     * @return the value of public.alcohol_type.type_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol_type.type_name
     *
     * @param typeName the value for public.alcohol_type.type_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}