package vn.com.vti.bookshop.entity;

public class AlcoholCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol_company.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol_company.company_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol_company.invoice_number
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer invoiceNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol_company.id
     *
     * @return the value of public.alcohol_company.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol_company.id
     *
     * @param id the value for public.alcohol_company.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol_company.company_name
     *
     * @return the value of public.alcohol_company.company_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol_company.company_name
     *
     * @param companyName the value for public.alcohol_company.company_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol_company.invoice_number
     *
     * @return the value of public.alcohol_company.invoice_number
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol_company.invoice_number
     *
     * @param invoiceNumber the value for public.alcohol_company.invoice_number
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setInvoiceNumber(Integer invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }
}