package vn.com.vti.bookshop.entity;

public class Alcohol {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol.name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol.price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol.type_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol.company_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.alcohol.alcohol_volume
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer alcoholVolume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol.id
     *
     * @return the value of public.alcohol.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol.id
     *
     * @param id the value for public.alcohol.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol.name
     *
     * @return the value of public.alcohol.name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol.name
     *
     * @param name the value for public.alcohol.name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol.price
     *
     * @return the value of public.alcohol.price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol.price
     *
     * @param price the value for public.alcohol.price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol.type_id
     *
     * @return the value of public.alcohol.type_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol.type_id
     *
     * @param typeId the value for public.alcohol.type_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol.company_id
     *
     * @return the value of public.alcohol.company_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol.company_id
     *
     * @param companyId the value for public.alcohol.company_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.alcohol.alcohol_volume
     *
     * @return the value of public.alcohol.alcohol_volume
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getAlcoholVolume() {
        return alcoholVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.alcohol.alcohol_volume
     *
     * @param alcoholVolume the value for public.alcohol.alcohol_volume
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setAlcoholVolume(Integer alcoholVolume) {
        this.alcoholVolume = alcoholVolume;
    }
}