package vn.com.vti.bookshop.entity;

import java.util.Date;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.customer_id
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.password
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.last_name
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.first_name
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.birth_day
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private Date birthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.address
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.tel_no
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.mail_address
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.customer.regist_datetime
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    private Date registDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.customer_id
     *
     * @return the value of public.customer.customer_id
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.customer_id
     *
     * @param customerId the value for public.customer.customer_id
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.password
     *
     * @return the value of public.customer.password
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.password
     *
     * @param password the value for public.customer.password
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.last_name
     *
     * @return the value of public.customer.last_name
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.last_name
     *
     * @param lastName the value for public.customer.last_name
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.first_name
     *
     * @return the value of public.customer.first_name
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.first_name
     *
     * @param firstName the value for public.customer.first_name
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.birth_day
     *
     * @return the value of public.customer.birth_day
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public Date getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.birth_day
     *
     * @param birthDay the value for public.customer.birth_day
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.address
     *
     * @return the value of public.customer.address
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.address
     *
     * @param address the value for public.customer.address
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.tel_no
     *
     * @return the value of public.customer.tel_no
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.tel_no
     *
     * @param telNo the value for public.customer.tel_no
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.mail_address
     *
     * @return the value of public.customer.mail_address
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public String getMailAddress() {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.mail_address
     *
     * @param mailAddress the value for public.customer.mail_address
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.customer.regist_datetime
     *
     * @return the value of public.customer.regist_datetime
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public Date getRegistDatetime() {
        return registDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.customer.regist_datetime
     *
     * @param registDatetime the value for public.customer.regist_datetime
     *
     * @mbg.generated Fri Nov 03 23:25:09 JST 2023
     */
    public void setRegistDatetime(Date registDatetime) {
        this.registDatetime = registDatetime;
    }
}