package vn.com.vti.bookshop.entity;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.alcohol_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer alcoholId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.amount
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.unit_price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.tax
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer tax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.order_detail.total_price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.id
     *
     * @return the value of public.order_detail.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.id
     *
     * @param id the value for public.order_detail.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.alcohol_id
     *
     * @return the value of public.order_detail.alcohol_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getAlcoholId() {
        return alcoholId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.alcohol_id
     *
     * @param alcoholId the value for public.order_detail.alcohol_id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setAlcoholId(Integer alcoholId) {
        this.alcoholId = alcoholId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.amount
     *
     * @return the value of public.order_detail.amount
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.amount
     *
     * @param amount the value for public.order_detail.amount
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.unit_price
     *
     * @return the value of public.order_detail.unit_price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.unit_price
     *
     * @param unitPrice the value for public.order_detail.unit_price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setUnitPrice(Integer unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.tax
     *
     * @return the value of public.order_detail.tax
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.tax
     *
     * @param tax the value for public.order_detail.tax
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setTax(Integer tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.order_detail.total_price
     *
     * @return the value of public.order_detail.total_price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.order_detail.total_price
     *
     * @param totalPrice the value for public.order_detail.total_price
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
}