package vn.com.vti.bookshop.entity;

import java.util.Date;

public class PaymentType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment_type.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment_type.payment_method_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String paymentMethodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment_type.payment_status
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String paymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.payment_type.payment_time
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Date paymentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment_type.id
     *
     * @return the value of public.payment_type.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment_type.id
     *
     * @param id the value for public.payment_type.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment_type.payment_method_name
     *
     * @return the value of public.payment_type.payment_method_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getPaymentMethodName() {
        return paymentMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment_type.payment_method_name
     *
     * @param paymentMethodName the value for public.payment_type.payment_method_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setPaymentMethodName(String paymentMethodName) {
        this.paymentMethodName = paymentMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment_type.payment_status
     *
     * @return the value of public.payment_type.payment_status
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment_type.payment_status
     *
     * @param paymentStatus the value for public.payment_type.payment_status
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.payment_type.payment_time
     *
     * @return the value of public.payment_type.payment_time
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.payment_type.payment_time
     *
     * @param paymentTime the value for public.payment_type.payment_time
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }
}