package vn.com.vti.bookshop.entity;

import java.util.ArrayList;
import java.util.List;

public class ShippingMethodExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public ShippingMethodExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameIsNull() {
            addCriterion("shipping_method_name is null");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameIsNotNull() {
            addCriterion("shipping_method_name is not null");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameEqualTo(String value) {
            addCriterion("shipping_method_name =", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameNotEqualTo(String value) {
            addCriterion("shipping_method_name <>", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameGreaterThan(String value) {
            addCriterion("shipping_method_name >", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameGreaterThanOrEqualTo(String value) {
            addCriterion("shipping_method_name >=", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameLessThan(String value) {
            addCriterion("shipping_method_name <", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameLessThanOrEqualTo(String value) {
            addCriterion("shipping_method_name <=", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameLike(String value) {
            addCriterion("shipping_method_name like", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameNotLike(String value) {
            addCriterion("shipping_method_name not like", value, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameIn(List<String> values) {
            addCriterion("shipping_method_name in", values, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameNotIn(List<String> values) {
            addCriterion("shipping_method_name not in", values, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameBetween(String value1, String value2) {
            addCriterion("shipping_method_name between", value1, value2, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingMethodNameNotBetween(String value1, String value2) {
            addCriterion("shipping_method_name not between", value1, value2, "shippingMethodName");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIsNull() {
            addCriterion("shipping_fee is null");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIsNotNull() {
            addCriterion("shipping_fee is not null");
            return (Criteria) this;
        }

        public Criteria andShippingFeeEqualTo(Integer value) {
            addCriterion("shipping_fee =", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotEqualTo(Integer value) {
            addCriterion("shipping_fee <>", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeGreaterThan(Integer value) {
            addCriterion("shipping_fee >", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("shipping_fee >=", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeLessThan(Integer value) {
            addCriterion("shipping_fee <", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeLessThanOrEqualTo(Integer value) {
            addCriterion("shipping_fee <=", value, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeIn(List<Integer> values) {
            addCriterion("shipping_fee in", values, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotIn(List<Integer> values) {
            addCriterion("shipping_fee not in", values, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeBetween(Integer value1, Integer value2) {
            addCriterion("shipping_fee between", value1, value2, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andShippingFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("shipping_fee not between", value1, value2, "shippingFee");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingIsNull() {
            addCriterion("time_until_shipping is null");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingIsNotNull() {
            addCriterion("time_until_shipping is not null");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingEqualTo(String value) {
            addCriterion("time_until_shipping =", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingNotEqualTo(String value) {
            addCriterion("time_until_shipping <>", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingGreaterThan(String value) {
            addCriterion("time_until_shipping >", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingGreaterThanOrEqualTo(String value) {
            addCriterion("time_until_shipping >=", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingLessThan(String value) {
            addCriterion("time_until_shipping <", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingLessThanOrEqualTo(String value) {
            addCriterion("time_until_shipping <=", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingLike(String value) {
            addCriterion("time_until_shipping like", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingNotLike(String value) {
            addCriterion("time_until_shipping not like", value, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingIn(List<String> values) {
            addCriterion("time_until_shipping in", values, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingNotIn(List<String> values) {
            addCriterion("time_until_shipping not in", values, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingBetween(String value1, String value2) {
            addCriterion("time_until_shipping between", value1, value2, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilShippingNotBetween(String value1, String value2) {
            addCriterion("time_until_shipping not between", value1, value2, "timeUntilShipping");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalIsNull() {
            addCriterion("time_until_arrival is null");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalIsNotNull() {
            addCriterion("time_until_arrival is not null");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalEqualTo(String value) {
            addCriterion("time_until_arrival =", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalNotEqualTo(String value) {
            addCriterion("time_until_arrival <>", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalGreaterThan(String value) {
            addCriterion("time_until_arrival >", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalGreaterThanOrEqualTo(String value) {
            addCriterion("time_until_arrival >=", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalLessThan(String value) {
            addCriterion("time_until_arrival <", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalLessThanOrEqualTo(String value) {
            addCriterion("time_until_arrival <=", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalLike(String value) {
            addCriterion("time_until_arrival like", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalNotLike(String value) {
            addCriterion("time_until_arrival not like", value, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalIn(List<String> values) {
            addCriterion("time_until_arrival in", values, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalNotIn(List<String> values) {
            addCriterion("time_until_arrival not in", values, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalBetween(String value1, String value2) {
            addCriterion("time_until_arrival between", value1, value2, "timeUntilArrival");
            return (Criteria) this;
        }

        public Criteria andTimeUntilArrivalNotBetween(String value1, String value2) {
            addCriterion("time_until_arrival not between", value1, value2, "timeUntilArrival");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.shipping_method
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 02 13:54:42 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.shipping_method
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}