package vn.com.vti.bookshop.entity;

public class ShippingMethod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shipping_method.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shipping_method.shipping_method_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String shippingMethodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shipping_method.shipping_fee
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private Integer shippingFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shipping_method.time_until_shipping
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String timeUntilShipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.shipping_method.time_until_arrival
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    private String timeUntilArrival;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shipping_method.id
     *
     * @return the value of public.shipping_method.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shipping_method.id
     *
     * @param id the value for public.shipping_method.id
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shipping_method.shipping_method_name
     *
     * @return the value of public.shipping_method.shipping_method_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getShippingMethodName() {
        return shippingMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shipping_method.shipping_method_name
     *
     * @param shippingMethodName the value for public.shipping_method.shipping_method_name
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setShippingMethodName(String shippingMethodName) {
        this.shippingMethodName = shippingMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shipping_method.shipping_fee
     *
     * @return the value of public.shipping_method.shipping_fee
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public Integer getShippingFee() {
        return shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shipping_method.shipping_fee
     *
     * @param shippingFee the value for public.shipping_method.shipping_fee
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setShippingFee(Integer shippingFee) {
        this.shippingFee = shippingFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shipping_method.time_until_shipping
     *
     * @return the value of public.shipping_method.time_until_shipping
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getTimeUntilShipping() {
        return timeUntilShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shipping_method.time_until_shipping
     *
     * @param timeUntilShipping the value for public.shipping_method.time_until_shipping
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setTimeUntilShipping(String timeUntilShipping) {
        this.timeUntilShipping = timeUntilShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.shipping_method.time_until_arrival
     *
     * @return the value of public.shipping_method.time_until_arrival
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public String getTimeUntilArrival() {
        return timeUntilArrival;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.shipping_method.time_until_arrival
     *
     * @param timeUntilArrival the value for public.shipping_method.time_until_arrival
     *
     * @mbg.generated Thu Nov 02 13:54:42 JST 2023
     */
    public void setTimeUntilArrival(String timeUntilArrival) {
        this.timeUntilArrival = timeUntilArrival;
    }
}