package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.CardCompany;
import vn.com.vti.bookshop.entity.CardCompanyExample;

public interface CardCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    long countByExample(CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByExample(CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByPrimaryKey(String cardCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insert(CardCompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insertSelective(CardCompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    List<CardCompany> selectByExample(CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    CardCompany selectByPrimaryKey(String cardCompanyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExampleSelective(@Param("row") CardCompany row, @Param("example") CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExample(@Param("row") CardCompany row, @Param("example") CardCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKeySelective(CardCompany row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.card_company
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKey(CardCompany row);
}