package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.Character;
import vn.com.vti.bookshop.entity.CharacterExample;

public interface CharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    long countByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByPrimaryKey(Integer characterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insert(Character row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insertSelective(Character row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    List<Character> selectByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    Character selectByPrimaryKey(Integer characterId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExampleSelective(@Param("row") Character row, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExample(@Param("row") Character row, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKeySelective(Character row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.character
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKey(Character row);
}