package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.MemberCard;
import vn.com.vti.bookshop.entity.MemberCardExample;

public interface MemberCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    long countByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int deleteByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int deleteByPrimaryKey(Integer memberCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int insert(MemberCard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int insertSelective(MemberCard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    List<MemberCard> selectByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    MemberCard selectByPrimaryKey(Integer memberCardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByExampleSelective(@Param("row") MemberCard row, @Param("example") MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByExample(@Param("row") MemberCard row, @Param("example") MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByPrimaryKeySelective(MemberCard row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.member_card
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByPrimaryKey(MemberCard row);
}