package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.OrderDetail;
import vn.com.vti.bookshop.entity.OrderDetailExample;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    long countByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByPrimaryKey(Integer orderDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insert(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insertSelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    List<OrderDetail> selectByExample(OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    OrderDetail selectByPrimaryKey(Integer orderDetailNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExampleSelective(@Param("row") OrderDetail row, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExample(@Param("row") OrderDetail row, @Param("example") OrderDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKeySelective(OrderDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_detail
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKey(OrderDetail row);
}