package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.OrderHeader;
import vn.com.vti.bookshop.entity.OrderHeaderExample;

public interface OrderHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    long countByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int deleteByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int deleteByPrimaryKey(Integer orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int insert(OrderHeader row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int insertSelective(OrderHeader row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    List<OrderHeader> selectByExample(OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    OrderHeader selectByPrimaryKey(Integer orderNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByExampleSelective(@Param("row") OrderHeader row, @Param("example") OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByExample(@Param("row") OrderHeader row, @Param("example") OrderHeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByPrimaryKeySelective(OrderHeader row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.order_header
     *
     * @mbg.generated Fri Nov 03 18:18:06 JST 2023
     */
    int updateByPrimaryKey(OrderHeader row);
}