package vn.com.vti.bookshop.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.bookshop.entity.Product;
import vn.com.vti.bookshop.entity.ProductExample;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    long countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insert(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int insertSelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    Product selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExampleSelective(@Param("row") Product row, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKeySelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.product
     *
     * @mbg.generated Fri Nov 03 17:56:21 JST 2023
     */
    int updateByPrimaryKey(Product row);
}